# Generated by Django 2.2.6 on 2020-05-10 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=60)),
                ('num_try', models.IntegerField(default=0)),
                ('otp', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='nvuser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=60)),
                ('fullname', models.TextField()),
                ('lastname', models.TextField()),
            ],
        ),
    ]
