# Generated by Django 2.2.6 on 2020-05-10 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verify', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='otp',
            field=models.IntegerField(default=487569),
        ),
        migrations.AlterField(
            model_name='nvuser',
            name='fullname',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='nvuser',
            name='lastname',
            field=models.TextField(default=''),
        ),
    ]
