# Generated by Django 2.2.6 on 2020-05-10 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verify', '0002_auto_20200510_0704'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='otp_try',
            field=models.IntegerField(default=0),
        ),
    ]
